export default {
  container: {
    flex: 1,
    flexDirection: 'column',
  },
  scannerBorder: {
    flex: 1,
    position: "absolute",
    height: '100%',
    width: '100%',
  },
  text: {
    paddingTop: '35%',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 36,
    fontWeight: '500',
    lineHeight: 46,
    zIndex: 10,
    color: 'rgb(111, 218, 242)',
  },
  xButton: {
    flex: 1,
    position: "absolute",
    top: "10%",
    right: "10%",
    zIndex: 100,
  },
  overlay: {
    flex: 1,
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: 280,
    borderBottomWidth: 280,
    borderLeftWidth: 40,
    borderRightWidth: 40,
    borderColor: "#0E1C4B",
    opacity: 0.56,
    zIndex: 5,
  },
  cornerTL: {
    flex: 1,
    position: "absolute",
    top: 280,
    left: 40,
    zIndex: 10,
  },
  cornerTR: {
    flex: 1,
    position: "absolute",
    top: 280,
    right: 40,
    zIndex: 10,
  },
  cornerBR: {
    flex: 1,
    position: "absolute",
    bottom: 280,
    right: 40,
    zIndex: 10,
  },
  cornerBL: {
    flex: 1,
    position: "absolute",
    bottom: 280,
    left: 40,
    zIndex: 10,
  },
};
