export default {
  container: {
    flex: 1,
    flexDirection: 'column',
    position: "relative",
    backgroundColor: "#FFFFFF",
    color: '#000000',
    fontWeight: '500',
  },
  bannerContainer: {
    backgroundColor: 'black',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 96,
    paddingTop: 37,
    paddingHorizontal: 45,
  },
  bannerText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 19,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 12,
    paddingBottom: 6,
    paddingHorizontal: 21,
    height: 37,
    borderWidth: 1,
    borderColor: "#EFF1F4",
    backgroundColor: '#F6F6F9',
  },
  headerLabelLeft: {
    position: 'relative',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 19,
    color: '#BABFCC',
  },
  headerLabelRight: {
    position: 'relative',
    // alignSelf: 'flex-end',
    fontWeight: '200',
    fontSize: 14,
    lineHeight: 17,
    color: '#000000',
    textAlign: 'center',
    /* identical to box height */
    color: '#4F7484',
  },
  caloriesRemainingContainer: {
    height: 141,
    justifyContent: 'center',
  },
  caloriesRemainingHeader: {
    textAlign: 'center',
    fontWeight: '800',
    // paddingTop: 24,
    fontSize: 64,
    lineHeight: 76,
  },
  caloriesRemainingText: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19,
    textAlign: 'center',
    color: '#4F7484',
  },
  macroContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-around',
    marginVertical: 24,
    width: 273,
  },
  scrollViewContainer: {
    paddingHorizontal: 20,
    paddingTop: 6,
  },
  footerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 7,
    paddingBottom: 30,
    borderTopColor: '#EFEFEF',
    borderTopWidth: 1,
  },
  footerButtonTouchable: {
    backgroundColor: "clear",
    padding: 20,
  },
};
