export default {
  container: {
    flex: 1,
    flexDirection: 'column',
    position: "relative",
    backgroundColor: "#FFFFFF",
    // color: '#000000',
  },
  headerContainer: {
    flexDirection: 'row',
    paddingTop: 55,
    paddingHorizontal: 18,
    justifyContent: 'space-between',
    alignContent: 'flex-start',
    // paddingBottom: 32,
  },
  headerText: {
    textAlign: "center",
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 21,
  },
  itemHeaderContainer: {
    paddingTop: 32,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  itemHeaderText: {
    fontWeight: '600',
    fontSize: 32,
    lineHeight: 38,
    color: '#0A0A0A',
  },
  itemHeaderType: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 17,
    color: '#4F7484',
  },
  itemInfoInputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#EFF0F4',
    marginHorizontal: 20,
  },
  itemInfoInputLabel: {
    paddingTop: 18,
    paddingBottom: 16,
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
    color: '#000000',
  },
  itemInfoInput: {
    paddingTop: 18,
    paddingBottom: 16,
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 19,
    color: '#CF1E93',
  },
  smallHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 12,
    paddingBottom: 6,
    paddingHorizontal: 20,
    height: 37,
    borderWidth: 1,
    borderColor: "#EFF1F4",
    backgroundColor: '#F6F6F9',
  },
  smallHeaderLabelLeft: {
    position: 'relative',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 19,
    color: '#BABFCC',
  },
  caloriesContainer: {
    height: 141,
    justifyContent: 'center',
  },
  caloriesHeader: {
    textAlign: 'center',
    fontWeight: '800',
    // paddingTop: 24,
    fontSize: 64,
    lineHeight: 76,
  },
  macroContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-around',
    marginVertical: 24,
    width: 273,
  },
  footerButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    height: 96,
    width: '100%',
    backgroundColor: '#E11111',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerButtonText: {
    paddingHorizontal: 10,
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 21,
    color: 'white',
  },
};
