export default {
  container: {
    flex: 1,
    flexDirection: 'column',
    position: "relative",
    // height: "100%",
    paddingHorizontal: 20,
    backgroundColor: "#E5E5E5",
    color: '#000000',
  },
  header: {
    textAlign: "center",
    paddingTop: "30%",
    fontSize: 36,
    fontWeight: '500',
    lineHeight: 46,
  },
  text: {
    textAlign: "left",
    paddingTop: "18%",
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
  },
  input: {
    top: 10,
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderWidth: 1,
    borderRadius: 4,
    borderStyle: "solid",
    borderColor: "#D2DBE2",
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
    color: "#B8B6B6",
  },
  buttonContainer: {
    position: "absolute",
    flexDirection: 'row',
    justifyContent: "center",
    alignItems: "center",
    bottom: 0,
    paddingBottom: "30%",
    paddingHorizontal: 40,
  },
};
