export default {
  container: {
    flex: 1,
    flexDirection: 'column',
    position: "relative",
    paddingHorizontal: 20,
    backgroundColor: "#FFFFFF",
    color: '#000000',
  },
  headerContainer: {
    flexDirection: 'row',
    paddingTop: 55,
    justifyContent: 'space-between',
    alignContent: 'flex-start',
  },
  headerText: {
    textAlign: "center",
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 21,
  },
  searchContainer: {
    marginTop: 20,
    borderStyle: "solid",
    borderRadius: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F6F9FA',
  },
  searchIcon: {
    paddingLeft: 10,
  },
  input: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19,
    flex: 1,
    padding: 10,
  },
  resultsContainer: {
    // flex: 1,
    // position: "absolute",
    // flexDirection: 'row',
    // justifyContent: "center",
    // alignItems: "center",
    // bottom: 0,
    // paddingBottom: "30%",
    // paddingHorizontal: 40,
  },
  resultsHeader: {
    paddingTop: 32,
    paddingBottom: 20,
    fontWeight: '600',
    fontSize: 32,
    lineHeight: 38,
  },
  scrollView: {
    // flex: 1,
    // paddingVertical:  100,
    marginBottom: 220,
  },
  itemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemText: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19,
    paddingBottom: 6,
  },
  itemServing: {
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
    paddingBottom: 20,
    color: '#4F7484',
  },
  footerContainer: {
    position: 'absolute',
    height: 100,
    marginHorizontal: 20,
    // paddingTop: 100,
    width: '100%',
    bottom: 0,
  },
};
