export default {
  container: {
    flex: 1,
    flexDirection: 'column',
    position: "relative",
    // height: "100%",
    paddingHorizontal: 20,
    backgroundColor: "#E5E5E5",
    color: '#000000',
  },
  header: {
    textAlign: "center",
    paddingTop: "35%",
    paddingBottom: "25%",
    fontSize: 36,
    fontWeight: '500',
    lineHeight: 46,
  },
  text: {
    textAlign: "left",
    // paddingTop: 0,
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
    color: '#B8B6B6'
  },
  inputContainer: {
    paddingBottom: 15,
  },
  input: {
    height: 50,
    paddingLeft: 15,
    marginVertical: 2,
    borderWidth: 1,
    borderRadius: 4,
    borderStyle: "solid",
    borderColor: "#D2DBE2",
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
    textTransform: 'uppercase',
  },
  inputText: {
    textAlign: "left",
    // paddingTop: 0,
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
    color: '#000000'
  },
  buttonContainer: {
    position: "absolute",
    flexDirection: 'row',
    justifyContent: "center",
    alignItems: "center",
    bottom: 0,
    paddingBottom: "30%",
    paddingHorizontal: 40,
  },
};
