export default {
  buttonContainer: {
    flex: 1,
    position: "relative",
    flexDirection: 'row',
    justifyContent: "center",
    alignItems: "center",
    bottom: 0,
    paddingBottom: "30%",
  },
  container: {
    flex: 1,
    margin: 20,
    alignItems: 'center',
    borderRadius: 4,
    borderStyle: "solid",
  },
  containerCTA: {
    flex: 1,
    position: 'relative',
    margin: 20,
    alignItems: 'center',
    borderRadius: 4,
    borderStyle: "solid",
    backgroundColor: "#000000",
  },
  buttonText: {
    paddingVertical: 22,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 21,
  },
  buttonTextCTA: {
    paddingVertical: 22,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 21,
    color: '#FFFFFF',
  },
};
