export default {
  container: {
    flex: 1,
    flexDirection: 'column',
    position: "relative",
    paddingHorizontal: 20,
    backgroundColor: "#FFFFFF",
    color: '#000000',
  },
  header: {
    paddingTop: "30%",
    paddingBottom: 20,
    fontSize: 36,
    fontWeight: '500',
    lineHeight: 46,
  },
  text: {
    textAlign: "left",
    paddingBottom: 15,
    color: '#4F7484',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 19,
  },
  inputContainer: {
    marginTop: 30,
    paddingTop: 20,
    borderStyle: 'solid',
    borderTopWidth: 1,
    borderTopColor: '#D0D3DB',
  },
  inputLabel: {
    textAlign: "left",
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 23,
  },
  input: {
    padding: 8,
    marginBottom: 10,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19,
    backgroundColor: '#F6F9FA',
  },
  buttonContainer: {
    position: "absolute",
    flexDirection: 'row',
    // justifyContent: "center",
    // alignItems: "center",
    bottom: 0,
    left: 20,
    paddingBottom: 35,
  },
};
